/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/night_sky.glb -o app/components/models/NightSkyModel.tsx --transform --shadows --resolution 512 --keepmeshes --instance --types 
Files: public/models/night_sky.glb [1.37MB] > /Users/sanchitgarg/Desktop/my portfolio creation/sanchit-portfolio/app/components/models/night_sky-transformed.glb [47.8KB] (97%)
Author: commonfactory (https://sketchfab.com/commonfactory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/night-sky-visible-spectrum-monochromatic-cfb156f03a7341b8a0a0ba0445ca742d
Title: Night Sky Visible Spectrum Monochromatic
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function NightSkyModel(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/night_sky-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} rotation={[-0.354, 0.348, 0.118]} scale={0.003}>
        <meshStandardMaterial {...materials.material} side={THREE.DoubleSide} emissive="#1e3a8a" emissiveIntensity={2} />
      </mesh>
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} rotation={[-0.436, 0.415, -2.967]} scale={0.308}>
        <meshStandardMaterial {...materials.Material} side={THREE.DoubleSide} emissive="#3b82f6" emissiveIntensity={1} />
      </mesh>
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} rotation={[-0.376, 1.085, -2.617]} scale={0.308}>
        <meshStandardMaterial {...materials['Material.001']} side={THREE.DoubleSide} emissive="#60a5fa" emissiveIntensity={1} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/night_sky-transformed.glb')
